name: 'Datadog Synthetic'
description: 'Scheduler for Datadog Synthetic'
inputs:
  datadog-api-key:
    description: 'API Key for Datadog'
    required: true
    default: ${{secrets.DATADOG_API_KEY}}
  datadog-application-key:
    description: 'Application Key for Datadog'
    required: true
    default: ${{secrets.DATADOG_APPLICATION_KEY}}
outputs:
  result: # id of output
    description: 'The Result'
runs:
  using: 'node12'
  main: 'dist/index.js'