name: 'Datadog Synthetic'
description: 'Scheduler for Datadog Synthetic'
inputs:
  api-url:
    description: 'The URL of the API, the default is us'
    default: 'https://api.datadoghq.com'
  datadog-api-key:
    description: 'API Key for Datadog'
    required: true
  datadog-application-key:
    description: 'Application Key for Datadog'
    required: false
outputs:
  result: # id of output
    description: 'The Result'
runs:
  using: 'node12'
  main: 'dist/index.js'