on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test Job for Datadog Synthetic
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          datadog-api-key: ${{secrets.DATADOG_API_KEY}}
          datadog-application-key: ${{secrets.DATADOG_APPLICATION_KEY}}
          public-ids: "['vrz-9c5-a9z']"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.result }}"