on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test Job for Datadog Synthetic
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Action step
        uses: ./
        id: test
        with:
          datadog-api-key: ${{secrets.DATADOG_API_KEY}}
          datadog-application-key: ${{secrets.DATADOG_APPLICATION_KEY}}
          # public-ids: "vrz-9c5-a9z,r69-v3v-28q"
          tags: "sleep@night"
          new-status: "live"